//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterCam {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterCam.text", typeof(text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello. I found a nice and useful application you might like: \n * WP7 : http://windowsphone.com/s?appid=9364b628-0c35-4823-80df-9673dcb6a62e \n  * Android : https://market.android.com/details?id=fr.naya.
        /// </summary>
        public static string EMAIL_MESSAGE {
            get {
                return ResourceManager.GetString("EMAIL_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat Calculator for Windows Phone.
        /// </summary>
        public static string EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to europe.
        /// </summary>
        public static string FLAG {
            get {
                return ResourceManager.GetString("FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excl. TAX.
        /// </summary>
        public static string HT {
            get {
                return ResourceManager.GetString("HT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ranking.
        /// </summary>
        public static string RANK {
            get {
                return ResourceManager.GetString("RANK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://windowsphone.com/s?appid=9364b628-0c35-4823-80df-9673dcb6a62e.
        /// </summary>
        public static string SHARE_LINK {
            get {
                return ResourceManager.GetString("SHARE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best Android Vat Calculator is now on WindowsPhone.
        /// </summary>
        public static string SHARE_MESSAGE {
            get {
                return ResourceManager.GetString("SHARE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Calculator for Windows Phone.
        /// </summary>
        public static string SHARE_TITLE {
            get {
                return ResourceManager.GetString("SHARE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sms.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello. I found a nice and useful application you might like: http://windowsphone.com/s?appid=9364b628-0c35-4823-80df-9673dcb6a62e.
        /// </summary>
        public static string SMS_MESSAGE {
            get {
                return ResourceManager.GetString("SMS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incl TAX.
        /// </summary>
        public static string TTC {
            get {
                return ResourceManager.GetString("TTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string TVA {
            get {
                return ResourceManager.GetString("TVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string USER {
            get {
                return ResourceManager.GetString("USER", resourceCulture);
            }
        }
    }
}
